#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-status --diff-filter d -- '*.go' | awk '{ print $2 }')

STASH_NAME="pre-commit-$(date +%s)"
git stash save -q -k --keep-index $STASH_NAME

$PWD/.githooks/lint
LINTSTATUS=$?

$PWD/.githooks/imports
IMPORTSTATUS=$?

$PWD/.githooks/vet
VETSTATUS=$?

$PWD/.githooks/tests
TESTSTATUS=$?

git checkout -- .
git stash pop -q $(git stash list | grep $STASH_NAME | cut -d: -f1)

printf "\n`tput bold`PreChecks:`tput sgr0`\n"
if [[ $LINTSTATUS != 0 || $IMPORTSTATUS != 0 || $TESTSTATUS != 0 || $VETSTATUS != 0 ]]; then
  printf "\t`tput setaf 1`[𐄂] Failed`tput sgr0`\n"
  exit 1
fi
printf "\t`tput setaf 2`[✓] Succeeded`tput sgr0`\n"
exit 0