#!/bin/sh

GOTEST=$GOPATH/bin/gotestsum

PASS=true

printf "\n`tput bold`Test:`tput sgr0`\n"
testoutput=$($GOTEST --format short-verbose)
if [[ $? != 0 ]]; then
  echo "$testoutput" | grep "^FAIL"| sed "s/FAIL/\\`tput setaf 1`[𐄂]/" | sed "s/$/\\`tput sgr0`/g;" | awk '{print "\t"$0}'  | xargs -0 printf
  echo "$testoutput" | grep "^DONE"| sed "s/DONE/\\`tput setaf 3`DONE/" | sed "s/$/\\`tput sgr0`/g;" | awk '{print "\n\t"$0}'  | xargs -0 printf
  PASS=false
else
  echo "$testoutput" | grep "^PASS" | sed "s/\.Test.*.\$//" |  sed "s/ (cached)//" | awk \!'x[$0]++' |sed "s/PASS/\\`tput setaf 2`[✓]/" | sed "s/$/\\`tput sgr0`/g;" | awk '{print "\t"$0}' | xargs -0 printf
  echo "$testoutput" | grep "^DONE"| sed "s/DONE/\\`tput setaf 6`DONE/" | sed "s/$/\\`tput sgr0`/g;" | awk '{print "\n\t"$0}'  | xargs -0 printf
fi

if ! $PASS; then
  exit 1
fi

exit 0